require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-slim
  - sevencop

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - spec/**/*.slim
  NewCops: enable
  TargetRubyVersion: 2.6

Gemspec/RequireMFA:
  Enabled: false

Metrics:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/rubocop-slim.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Sevencop/AutoloadOrdered:
  Enabled: true

Sevencop/HashElementOrdered:
  Enabled: true

Sevencop/MethodDefinitionArgumentsMultiline:
  Enabled: true

Sevencop/MethodDefinitionKeywordArgumentOrdered:
  Enabled: true

Sevencop/MethodDefinitionOrdered:
  Enabled: true

Style/Documentation:
  Enabled: false
